# Generated by Django 3.2.4 on 2021-07-08 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AddressTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificativo', models.CharField(max_length=400)),
                ('via', models.CharField(max_length=400)),
                ('cap', models.CharField(max_length=5)),
                ('citta', models.CharField(max_length=400)),
                ('provincia', models.CharField(max_length=2)),
                ('note', models.TextField(blank=True, null=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirizzo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'indirizzo',
                'verbose_name_plural': 'indirizzi',
            },
        ),
        migrations.CreateModel(
            name='FoodDonation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'Cibo Cotto'), (2, 'Cibo Confezionato'), (3, 'Farmaci')])),
                ('qty', models.IntegerField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now_add=True)),
                ('status', models.TextField(choices=[('D', 'Disponibile'), ('P', 'Prenotato'), ('C', 'Consegnato')], max_length=1)),
                ('indirizzo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirizzo', to='donatore.addresstable')),
                ('user_donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donazione', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donazione Cibo',
                'verbose_name_plural': 'Donazioni Cibo',
                'ordering': ['date_creation'],
            },
        ),
    ]
