# Generated by Django 3.2.4 on 2021-07-26 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donatore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooddonation',
            name='status',
            field=models.TextField(choices=[('D', 'Disponibile'), ('P', 'Prenotato'), ('C', 'Consegnato'), ('T', 'Temporaneamente non disponibile')], max_length=1),
        ),
    ]
