# Generated by Django 3.2.4 on 2021-07-23 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donatore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('id_donazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_donazione', to='donatore.fooddonation')),
                ('user_assoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordinetemporaneo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordine Temporaneo',
                'verbose_name_plural': 'Ordini Temporanei',
                'ordering': ['date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Ordini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_confimation', models.DateTimeField(auto_now_add=True)),
                ('id_donazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordine', to='donatore.fooddonation')),
                ('user_assoc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_assoc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ordine',
                'verbose_name_plural': 'Ordini',
                'ordering': ['date_confimation'],
            },
        ),
    ]
