# Generated by Django 3.2.5 on 2021-11-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associazione', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordini',
            name='donatore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordini',
            name='num_ordine',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='ordtemp',
            name='donatore',
            field=models.IntegerField(default=0),
        ),
    ]
