# Generated by Django 3.2.5 on 2021-11-11 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donatore', '0003_notification'),
        ('associazione', '0002_auto_20211111_2212'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordini',
            name='id_donazione',
        ),
        migrations.CreateModel(
            name='Dettaglio_Ordini',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_donazione', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donazioni', to='donatore.fooddonation')),
                ('id_ordine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordini', to='associazione.ordini')),
            ],
        ),
    ]

