# Generated by Django 3.2.5 on 2021-11-15 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donatore', '0003_notification'),
        ('associazione', '0003_auto_20211111_2238'),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('carrier', models.TextField(max_length=200)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indirizzo_destinazione', to='donatore.addresstable')),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dati_donazione', to='associazione.ordini')),
            ],
            options={
                'verbose_name': 'Documento di Trasporto',
                'verbose_name_plural': 'Documenti di Trasporto',
            },
        ),
    ]
