# Generated by Django 3.2.9 on 2021-11-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('associazione', '0004_donorreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='dettaglio_ordini',
            name='quant',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ordtemp',
            name='quant',
            field=models.IntegerField(default=0),
        ),
    ]
